pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK17'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn -B clean compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn -B test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }


        stage('Code Coverage') {
            steps {
                sh 'mvn -B verify'
            }
            post {
                success {
                    publishCoverage adapters: [
                            jacocoAdapter('target/site/jacoco/jacoco.xml')
                    ]
                }
            }
        }


        stage('Package') {
            steps {
                sh 'mvn -B package'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
        }
    }
}